services:
  nexus-change-api:
    image: rogeriofontes/nexus-change-api:v0.0.1
    container_name: nexus-change-api
    environment:
      DATABASE_PASSWORD: Postgres2024!
      DATABASE_URL: jdbc:postgresql://nexus-postgres:5432/ns-change-db
      DATABASE_USERNAME: postgres
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092   # <-- AQUI ajustado (antes estava kafka:9092)
      PAYMENT_PROVIDER: provider-local
      SECURITY_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SWAGGER_API_URL: http://nexus-change-api:9933
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    ports:
      - "9933:9933"
    networks:
      - nexus-network

networks:
  nexus-network:
    external: true
    name: nexus-network