version: "3.8"

services:
  nexus-postgres:
    image: postgres:16.3-alpine
    container_name: nexus-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Postgres2024!
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nexus-network

  nexus-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexus-pgadmin
    restart: always
    depends_on:
      - nexus-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: infra@nexus.com.br
      PGADMIN_DEFAULT_PASSWORD: PgAdmin2024!
    ports:
      - "16543:80"
    networks:
      - nexus-network
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - nexus-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - nexus-network
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - nexus-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - nexus-network

  nexus-client-api:
    image: rogeriofontes/nexus-client-api:v.0.1
    container_name: nexus-client-api
    environment:
      DATABASE_URL: jdbc:postgresql://nexus-postgres:5432/ns-client-db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Postgres2024!
      SECURITY_JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      API_GATEWAY_URL_PRIVACY_NOTIFICATION_STATUS: http://nexus-privacy-notification-status-api:9916/status
      AWS_REGION: us-east-1
    ports:
      - "9912:9912"
    depends_on:
      - nexus-postgres
    networks:
      - nexus-network

  nexus-company-api:
    image: rogeriofontes/nexus-company-api:v.0.1
    container_name: nexus-company-api
    environment:
      DATABASE_URL: jdbc:postgresql://nexus-postgres:5432/ns-company-db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Postgres2024!
      API_GATEWAY_CLIENT_URL: http://nexus-client-api:9912/clientes
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      AWS_REGION: us-east-1
    ports:
      - "9913:9913"
    depends_on:
      - nexus-postgres
      - nexus-client-api
    networks:
      - nexus-network

  nexus-product-api:
    image: rogeriofontes/nexus-product-api:v.0.1
    container_name: nexus-product-api
    environment:
      DATABASE_URL: jdbc:postgresql://nexus-postgres:5432/ns-product-db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Postgres2024!
      API_GATEWAY_CLIENT_URL: http://nexus-client-api:9912/clientes
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    ports:
      - "9914:9914"
    depends_on:
      - nexus-postgres
    networks:
      - nexus-network

  nexus-inventory-api:
    image: rogeriofontes/nexus-inventory-api:v.0.1
    container_name: nexus-inventory-api
    environment:
      DATABASE_URL: jdbc:postgresql://nexus-postgres:5432/ns-inventory-db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Postgres2024!
      API_GATEWAY_PRODUCT_URL: http://nexus-product-api:9915/products
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
      API_GATEWAY_URL_PRIVACY_NOTIFICATION_STATUS: http://nexus-privacy-notification-status-api:9916/status
    ports:
      - "9915:9915"
    depends_on:
      - nexus-postgres
      - nexus-product-api
    networks:
      - nexus-network

networks:
  nexus-network:
    driver: bridge

volumes:
  postgres-data:
  kafka-data: