CREATE DATABASE IF NOT EXISTS "ns-client-db";
CREATE DATABASE IF NOT EXISTS "ns-company-db";
CREATE DATABASE IF NOT EXISTS "ns-product-db";
CREATE DATABASE IF NOT EXISTS "ns-inventory-db";
CREATE DATABASE IF NOT EXISTS "ns-order-db";
CREATE DATABASE IF NOT EXISTS "ns-transaction-db";